/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicAuthRouteImport } from './routes/(public)/auth'
import { Route as protectedDashboardRouteImport } from './routes/(protected)/dashboard'
import { Route as protectedSettingsRouteRouteImport } from './routes/(protected)/settings/route'
import { Route as protectedSettingsIndexRouteImport } from './routes/(protected)/settings/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as protectedSettingsOrganizationRouteImport } from './routes/(protected)/settings/organization'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicAuthRoute = publicAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => publicRouteRoute,
} as any)
const protectedDashboardRoute = protectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedSettingsRouteRoute = protectedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedSettingsIndexRoute = protectedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedSettingsRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedSettingsOrganizationRoute =
  protectedSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => protectedSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/settings': typeof protectedSettingsRouteRouteWithChildren
  '/dashboard': typeof protectedDashboardRoute
  '/auth': typeof publicAuthRoute
  '/': typeof publicIndexRoute
  '/settings/organization': typeof protectedSettingsOrganizationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/settings/': typeof protectedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof protectedDashboardRoute
  '/auth': typeof publicAuthRoute
  '/': typeof publicIndexRoute
  '/settings/organization': typeof protectedSettingsOrganizationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/settings': typeof protectedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(protected)/settings': typeof protectedSettingsRouteRouteWithChildren
  '/(protected)/dashboard': typeof protectedDashboardRoute
  '/(public)/auth': typeof publicAuthRoute
  '/(public)/': typeof publicIndexRoute
  '/(protected)/settings/organization': typeof protectedSettingsOrganizationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(protected)/settings/': typeof protectedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/dashboard'
    | '/auth'
    | '/'
    | '/settings/organization'
    | '/api/auth/$'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/auth'
    | '/'
    | '/settings/organization'
    | '/api/auth/$'
    | '/settings'
  id:
    | '__root__'
    | '/(protected)'
    | '/(public)'
    | '/(protected)/settings'
    | '/(protected)/dashboard'
    | '/(public)/auth'
    | '/(public)/'
    | '/(protected)/settings/organization'
    | '/api/auth/$'
    | '/(protected)/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/auth': {
      id: '/(public)/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof publicAuthRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(protected)/dashboard': {
      id: '/(protected)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/settings': {
      id: '/(protected)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof protectedSettingsRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/settings/': {
      id: '/(protected)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof protectedSettingsIndexRouteImport
      parentRoute: typeof protectedSettingsRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/settings/organization': {
      id: '/(protected)/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof protectedSettingsOrganizationRouteImport
      parentRoute: typeof protectedSettingsRouteRoute
    }
  }
}

interface protectedSettingsRouteRouteChildren {
  protectedSettingsOrganizationRoute: typeof protectedSettingsOrganizationRoute
  protectedSettingsIndexRoute: typeof protectedSettingsIndexRoute
}

const protectedSettingsRouteRouteChildren: protectedSettingsRouteRouteChildren =
  {
    protectedSettingsOrganizationRoute: protectedSettingsOrganizationRoute,
    protectedSettingsIndexRoute: protectedSettingsIndexRoute,
  }

const protectedSettingsRouteRouteWithChildren =
  protectedSettingsRouteRoute._addFileChildren(
    protectedSettingsRouteRouteChildren,
  )

interface protectedRouteRouteChildren {
  protectedSettingsRouteRoute: typeof protectedSettingsRouteRouteWithChildren
  protectedDashboardRoute: typeof protectedDashboardRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedSettingsRouteRoute: protectedSettingsRouteRouteWithChildren,
  protectedDashboardRoute: protectedDashboardRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicAuthRoute: typeof publicAuthRoute
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicAuthRoute: publicAuthRoute,
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  protectedRouteRoute: protectedRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
